### ISSUE TITLE
how should i use this plugin if my drone was not in the k8s cluster

### ISSUE THREAD

**Issue by cherry4477** [geofeedia/drone-k8s#1]

**Comment by austenLacy** [comment]
@cherry4477 that's a good question that we inevitably knew would come up that we haven't solved because we haven't had a need to. However, you could try manually putting the k8s certs directly on the machine that is running Drone, copy them during the build step into the shared `/drone` directory that Drone mounts into each child container that it spawns, and then pass in the paths to those certs via the plugin params. That's actually how we do it, except we don't have to manually place the k8s certs on the machine running drone since k8s does that for us automatically.

For example:

```
build:
    image: quay.io/geofeedia/node:5.7.0
    pull: true
    when:
        branch: 1.*
    volumes:
       # mount /etc/kubernetes/ssl on the host machine running Drone into the build container
        - /etc/kubernetes/ssl/:/etc/kubernetes/ssl/
    commands:
        - mkdir -p /drone/.ssl/
        # copy the k8s ssl directory into the shared/mounted /drone dir for subsequent drone steps
        - cp -a /etc/kubernetes/ssl/. /drone/.ssl/
        - npm install --only=dev
        - npm run dist

publish:
    docker:develop:
        environment:
            - DOCKER_LAUNCH_DEBUG=true
        registry: quay.io
        username: "$$QUAY_USERNAME"
        password: "$$QUAY_PASSWORD"
        email: robo@geofeedia.com
        repo: geofeedia/some-services
        tag: v1-$$COMMIT
        file: dist/Dockerfile
        context: dist/
        storage_driver: overlay
        when:
            branch: 1.*

    drone-k8s:
        image: quay.io/geofeedia/drone-k8s:1.0.0
        replication_controller: my-rc-v1
        namespace: my-ns
        docker_image: quay.io/geofeedia/some-services:v1-$$COMMIT
        path_to_cert_authority: /drone/.ssl/ca.pem
        path_to_client_key: /drone/.ssl/worker-key.pem
        path_to_client_cert: /drone/.ssl/worker.pem
        when:
            branch: 1.*
```
